# Generated by Django 4.2 on 2023-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_1', models.CharField(max_length=300)),
                ('answer_2', models.CharField(max_length=300)),
                ('answer_3', models.CharField(max_length=300)),
                ('answer_4', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Test Question',
            },
        ),
    ]
