# Generated by Django 4.2 on 2023-05-01 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silky', '0002_rename_testquestionmodel_testquestion_testanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestAnswers',
            new_name='TestAnswer',
        ),
    ]
